[settings]
lockfile = true
idiomatic_version_file_enable_tools = ["node"]

[tools]
hugo = "0.153.1"
"aqua:pnpm/pnpm" = "10.28.1"
"github:houseabsolute/precious" = "0.10.1"
"github:sass/dart-sass" = "1.97.3"
