name = "dev-site"
pages_build_output_dir = "public"
compatibility_date = "2025-12-22"

[vars]
HUGO_VERSION = "0.153.1"

[env.production.vars]
CF_PAGES_URL = "https://dev.maxmind.com/"
HUGO_VERSION = "0.153.1"
