name: Firebase - Production

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/firebase-production.yml'
      - 'content/**'
      - 'functions/**'
      - 'gatsby/firebase/firebase.json'
      - 'gatsby/src/**'

jobs:
  production-build-test-deploy:
    name: Production - Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action
      - name: Cache Node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test:unit

      - name: Run accessibility tests
        run: yarn test:a11y

      - name: Build
        run: GATSBY_URL=https://dev.maxmind.com yarn build

      - name: Deploy Firebase preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.PRODUCTION_FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ secrets.PRODUCTION_FIREBASE_PROJECT_ID }}"
          channelId: live

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PRODUCTION_FIREBASE_PROJECT_ID }}
          service_account_key: ${{ secrets.PRODUCTION_FIREBASE_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Deploy all other Firebase resources
        run: yarn firebase deploy --except hosting --project ${{ secrets.PRODUCTION_FIREBASE_PROJECT_ID }}
