name: Precious
permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  code-formatting:
    env:
      BASE_REF: ${{ github.base_ref }}
    runs-on: ubuntu-latest
    name: Code Formatting
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Check that package-lock.json is valid JSON
        run: jq empty package-lock.json

      - run: npm ci

      - name: Fetch base ref
        if: ${{ github.event.pull_request }}
        run: git fetch origin "${BASE_REF}"

      - name: Install precious
        run: ./bin/install-precious /usr/local/bin

      - name: Select files
        id: select-files
        run: |
          if [[ -n "${{ github.event.pull_request.number }}" ]]; then
            echo "precious-args=--git-diff-from origin/${BASE_REF}" >> "$GITHUB_OUTPUT"
          else
            echo 'precious-args=--all' >> "$GITHUB_OUTPUT"
          fi

      - name: Lint files
        run: precious lint ${PRECIOUS_ARGS}
        env:
          PRECIOUS_ARGS: ${{ steps.select-files.outputs.precious-args }}
