name: Static Site

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/static-site.yml'
      - 'content/**'
      - 'gatsby/firebase/firebase.json'
      - 'gatsby/src/**'
  pull_request:

jobs:
  static-site:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action
      - name: Cache Node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test:unit

      - name: Run accessibility tests
        run: yarn test:a11y

      - name: Test coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: dkershner6/jest-coverage-commenter-action@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          test_command: "yarn test:unit --coverage"

      - name: Build
        run: yarn build

      - name: Deploy to staging project
        if: ${{ github.event_name == 'pull_request' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.STAGING_FIREBASE_SERVICE_ACCOUNT }}"
          expires: 7d
          projectId: "${secrets.STAGING_FIREBASE_PROJECT_ID}"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Deploy to production project
        if: ${{ github.event.pull_request.merged == true && github.ref == 'refs/heads/main' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.PRODUCTION_FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${secrets.PRODUCTION_FIREBASE_PROJECT_ID}"
          channelId: live
